# K3s Production Cluster - Dependabot Configuration
# Automatically updates dependencies with CI validation

version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "bogdandragosvasile"
    assignees:
      - "bogdandragosvasile"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Terraform providers
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "bogdandragosvasile"
    assignees:
      - "bogdandragosvasile"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"

  # Ansible collections
  - package-ecosystem: "pip"
    directory: "/ansible"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "bogdandragosvasile"
    assignees:
      - "bogdandragosvasile"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "ansible"
