# YAML Lint configuration for K3s Production Cluster
# Provides comprehensive YAML file linting

extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments
  comments:
    min-spaces-from-content: 1
    require-starting-space: true

  # Document start
  document-start:
    present: false

  # Document end
  document-end:
    present: false

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Empty values
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true

  # Hyphens
  hyphens:
    max-spaces-after: 1

  # Colons
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Commas
  commas:
    max-spaces-before: 0
    max-spaces-after: 1

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  # Comments indentation
  comments-indentation: {}

  # Key ordering
  key-ordering: disable

  # Octal values
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false

  # Quoted strings
  quoted-strings:
    quote-type: single
    check-keys: false
    required: false

  # Trailing spaces
  trailing-spaces: enable

  # Truthy
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

ignore: |
  .github/
  .git/
  terraform/
  backup/
  monitoring/
  vm-templates/
  *.backup
  *.example
