# K3s Cluster Configuration - Generated by scale-cluster.sh
environment = "development"
cluster_name = "k3s"

# Node counts
master_count = 1
worker_count = 1
storage_count = 0
lb_count = 0
gpu_count = 0

# Network configuration
network_cidr = "192.168.122.0/24"

# K3s configuration
k3s_version = "v1.33.4+k3s1"
k3s_token = ""

# Longhorn configuration
longhorn_version = "v1.7.2"

# MetalLB configuration
metallb_version = "v0.14.5"
metallb_ip_range = "192.168.122.100-192.168.122.150"
