---
- name: Install and Configure HAProxy on Load Balancers
  hosts: load_balancers
  gather_facts: yes
  vars:
    haproxy_version: "2.8.5"
    kubernetes_api_port: 6443
    haproxy_stats_port: 8404
    master_nodes:
      - "192.168.122.11"
      - "192.168.122.12" 
      - "192.168.122.13"

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: yes
      become: yes

    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
      become: yes

    - name: Enable HAProxy service
      systemd:
        name: haproxy
        enabled: yes
        state: started
      become: yes

    - name: Create HAProxy configuration directory
      file:
        path: /etc/haproxy
        state: directory
        mode: '0755'
      become: yes

    - name: Generate HAProxy configuration
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
        backup: yes
      become: yes
      notify: restart haproxy

    - name: Validate HAProxy configuration
      command: haproxy -c -f /etc/haproxy/haproxy.cfg
      become: yes
      changed_when: false

    - name: Start HAProxy service
      systemd:
        name: haproxy
        state: started
        enabled: yes
      become: yes

    - name: Wait for HAProxy to be ready
      wait_for:
        port: "{{ haproxy_stats_port }}"
        host: "{{ ansible_host }}"
        timeout: 30

    - name: Check HAProxy status
      systemd:
        name: haproxy
      become: yes
      register: haproxy_status

    - name: Display HAProxy status
      debug:
        msg: "HAProxy is {{ haproxy_status.status.ActiveState }} on {{ inventory_hostname }}"

    - name: Test HAProxy backend connectivity
      uri:
        url: "http://{{ ansible_host }}:{{ haproxy_stats_port }}/stats"
        method: GET
        status_code: 200
      register: haproxy_stats
      retries: 3
      delay: 5

    - name: Display HAProxy stats URL
      debug:
        msg: "HAProxy stats available at http://{{ ansible_host }}:{{ haproxy_stats_port }}/stats"

  handlers:
    - name: restart haproxy
      systemd:
        name: haproxy
        state: restarted
      become: yes

- name: Verify HAProxy Load Balancing
  hosts: localhost
  gather_facts: no
  vars:
    lb_ips:
      - "192.168.122.41"
      - "192.168.122.42"
    kubernetes_api_port: 6443

  tasks:
    - name: Test HAProxy connectivity to Kubernetes API
      uri:
        url: "https://{{ item }}:{{ kubernetes_api_port }}/api"
        method: GET
        validate_certs: no
        status_code: [200, 401, 403]  # 401/403 are expected without auth
        timeout: 10
      loop: "{{ lb_ips }}"
      register: haproxy_connectivity
      retries: 3
      delay: 5

    - name: Display HAProxy connectivity results
      debug:
        msg: "LB {{ item.item }}: {{ 'SUCCESS' if item.status == 200 or item.status == 401 or item.status == 403 else 'FAILED' }} (Status: {{ item.status }})"
      loop: "{{ haproxy_connectivity.results }}"

    - name: Verify all load balancers are accessible
      assert:
        that:
          - item.status == 200 or item.status == 401 or item.status == 403
        fail_msg: "HAProxy on {{ item.item }} is not accessible"
        success_msg: "HAProxy on {{ item.item }} is accessible"
      loop: "{{ haproxy_connectivity.results }}"
