name: Static Analysis & Security Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  pre-commit:
    name: Pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit hooks
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck yamllint
          pip install ansible ansible-lint
          pre-commit run --all-files || echo "Pre-commit completed with issues"

  secret-detection:
    name: Secret Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install detect-secrets
        run: |
          python -m pip install --upgrade pip
          pip install detect-secrets

      - name: Run detect-secrets scan
        run: |
          if [ ! -f .secrets.baseline ]; then
            detect-secrets scan --all-files --baseline .secrets.baseline
          fi
          
          detect-secrets scan --all-files --baseline .secrets.baseline || echo "Secrets scan completed"

  static-checks-gate:
    name: Static Checks Gate
    runs-on: ubuntu-latest
    needs: [pre-commit, secret-detection]
    if: always()
    outputs:
      passed: ${{ steps.gate-check.outputs.passed }}
    steps:
      - name: Evaluate static checks gate
        id: gate-check
        run: |
          PRE_COMMIT="${{ needs.pre-commit.result }}"
          SECRET_DETECTION="${{ needs.secret-detection.result }}"
          
          if [[ "$PRE_COMMIT" == "success" ]] && [[ "$SECRET_DETECTION" == "success" ]]; then
            echo "passed=true" >> $GITHUB_OUTPUT
            echo "✅ Static checks passed!"
          else
            echo "passed=false" >> $GITHUB_OUTPUT
            echo "❌ Static checks failed!"
          fi
