# K3s Production Cluster - Ansible Inventory
# Generated by Terraform

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=${ssh_public_key}
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3

# Master nodes
[masters]
k3s-production-master-1 ansible_host=${master1_ip}
k3s-production-master-2 ansible_host=${master2_ip}
k3s-production-master-3 ansible_host=${master3_ip}

# Worker nodes
[workers]
k3s-production-worker-1 ansible_host=${worker1_ip}
k3s-production-worker-2 ansible_host=${worker2_ip}
k3s-production-worker-3 ansible_host=${worker3_ip}

# Storage nodes
[storage]
k3s-production-storage-1 ansible_host=${storage1_ip}
k3s-production-storage-2 ansible_host=${storage2_ip}

# Load balancer nodes
[load_balancers]
k3s-production-lb-1 ansible_host=${lb1_ip}
k3s-production-lb-2 ansible_host=${lb2_ip}

# K3s cluster
[k3s_cluster:children]
masters
workers
load_balancers
storage

# All nodes
[all_nodes:children]
k3s_cluster
