# K3s Production Cluster - Ansible Inventory
# Generated by Terraform

all:
  children:
    masters:
      hosts:
        k3s-production-master-1:
          ansible_host: ${master1_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/k3s-cluster
        k3s-production-master-2:
          ansible_host: ${master2_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/k3s-cluster
        k3s-production-master-3:
          ansible_host: ${master3_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/k3s-cluster
      vars:
        node_role: master
        
    workers:
      hosts:
        k3s-production-worker-1:
          ansible_host: ${worker1_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/k3s-cluster
        k3s-production-worker-2:
          ansible_host: ${worker2_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/k3s-cluster
        k3s-production-worker-3:
          ansible_host: ${worker3_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/k3s-cluster
      vars:
        node_role: worker
        
    storage:
      hosts:
        k3s-production-storage-1:
          ansible_host: ${storage1_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/k3s-cluster
        k3s-production-storage-2:
          ansible_host: ${storage2_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/k3s-cluster
      vars:
        node_role: storage
        
    load_balancers:
      hosts:
        k3s-production-lb-1:
          ansible_host: ${lb1_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/k3s-cluster
        k3s-production-lb-2:
          ansible_host: ${lb2_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/k3s-cluster
      vars:
        node_role: load_balancer
