# K3s Production Cluster - Ansible Inventory
# Generated by Terraform

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3

# Master nodes
[masters]
k3s-production-master-1 ansible_host=192.168.122.11
k3s-production-master-2 ansible_host=192.168.122.12
k3s-production-master-3 ansible_host=192.168.122.13

# Worker nodes
[workers]
k3s-production-worker-1 ansible_host=192.168.122.21
k3s-production-worker-2 ansible_host=192.168.122.22
k3s-production-worker-3 ansible_host=192.168.122.23
k3s-production-worker-4 ansible_host=192.168.122.24
k3s-production-worker-5 ansible_host=192.168.122.25
k3s-production-worker-6 ansible_host=192.168.122.26

# Storage nodes
[storage]
k3s-production-storage-1 ansible_host=192.168.122.31
k3s-production-storage-2 ansible_host=192.168.122.32

# Load balancer nodes
[load_balancers]
k3s-production-lb-1 ansible_host=192.168.122.41
k3s-production-lb-2 ansible_host=192.168.122.42

# GPU nodes
[gpu]
k3s-production-gpu-1 ansible_host=192.168.122.51

# K3s cluster
[k3s_cluster:children]
masters
workers
load_balancers
storage
gpu

# All nodes
[all_nodes:children]
k3s_cluster
